### PR TITLE
Do not rely anymore on createFragment

### PR DESCRIPTION
**Pull request by MonsieurV**
The package [react-addons-create-fragment ](https://www.npmjs.com/package/react-addons-create-fragment) is deprecated and should not be used anymore.

The recommended approach is to use an array and key fragment elements (See https://github.com/facebook/react/issues/9207).
Seems we can do that easily!

An alternative would be to use the maybe-coming JSX syntax for fragments.
https://github.com/facebook/jsx/issues/84

Nevertheless it still imply creating an array of fragments (instead of an object as for `createFragment`).

PS. I was having issues with the last version of react-paginate and React r16 due to create-fragment, so I've done this PR. (I think it works on React r16 following the version of react-addons-create-fragment used. But better not use if we can do without: the installation is simpler)

PPS. I updated some bits to make it easier to test the project.

### CODE REVIEW

**Comment by MonsieurV** [comment]
The Node versions for running test have been updated: this was the reason of the failure (Node v4 was getting kind of old for some dependencies to be installed).

I think this is ready to be merged: been using it in production from more than one month now, with no issue.

It will make the module easier to run on React v16 and thus continue to make it attractive... as it rightfully does its job!

**Comment by MonsieurV** [comment]
I tested the last `react-paginate` version, which seems to have no issue anymore. (React being updated)

[Fragments](https://reactjs.org/docs/fragments.html) are out there to use, if we want.

@AdeleD do we merge it or we just drop it?

I can re-submit the PR with the conflicts resolved.

**Comment by AdeleD** [comment]
Ok, thank you.
I will merge it this weekend.

**Comment by MonsieurV** [comment]
Ok, for me this is ready to merge.

To recap:
* do not use the `react-addons-create-fragment` package, which is deprecated (use keys instead)
* update Babel presets (some where deprecated)
* update dev packages and configuration to run the demo with latest tools

This should make the project more easier to use in modern React projects.

**Comment by AdeleD** [comment]
Thank you very much for your work on this PR!

**Pull request merged**
