### PR TITLE
Fix "pagesBreaking[pagesBreaking.length - 1] is undefined"

### PR DESCRIPTION
**Pull request by DaWe35**
Fixed this error: 
image

Reproduce:
- switch to branch v9
- set `marginPagesDisplayed={0}`
- `npm start` and click the `2` or `next page` button

### CODE REVIEW

**Comment by MonsieurV** [comment]
Hi @DaWe35 

Thanks for the PR and good catch.

Can we just add a test to reproduce the case that break (before the fix)?

**Comment by MonsieurV** [comment]
Hi @DaWe35,

Thanks for the report and fix, I thought it was only for the `v9`, but it affects also the `master`, so I've just applied it directly. (Doing a pick was a bit overwhelming for 1 line; also there was this `href={1}`)

Thanks again!

@AdeleD this could be released as https://github.com/AdeleD/react-paginate/releases/tag/v8.0.3
I'll maybe do a minor (still v8)

**Comment by DaWe35** [comment]
Hi, thanks @MonsieurV and I'm sorry for the slow response, I forgot to write the test.

**Comment by KangYoosam** [comment]
I've experienced same issue.
Thanks @DaWe35 fixing it!

**Pull request closed without merging**
