### PR TITLE
Use prop-types instead of React.PropTypes

### PR DESCRIPTION
**Pull request by tristanoneil**
See [this post](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes) for more info.

### CODE REVIEW

**Comment by tristanoneil** [comment]
It appears CI is unhappy but I'm not able to get these specs to pass locally on `master` either.

**Comment by taylor-smith** [comment]
The tests pass locally for me, and I don't see where your code would have broken it. We could also take this opportunity to refactor TestUtils to react-dom/test-utils to avoid `Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.`

**Comment by mozmorris** [comment]
Any chance this might be merged soon?

**Comment by mozmorris** [comment]
🎉

**Comment by AdeleD** [comment]
Sorry for the delay

**Pull request merged**
