### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by codyc4321**
people trying a broken demo is wasteful, and the readme should reflect a broken demo until the instructions are fixed

### CODE REVIEW

**Comment by mundosk8** [comment]
It isn't broken. I just cloned it into my macOS and run as it should, nothing broken everythings works perfect, the problem is with your machine.

**Comment by codyc4321** [comment]
2 different machines? My node seems up to date too:

$ node --version
v8.0.0

I'm sorry, I highly doubt 2 different machines are the issue, although it's
possible

**Comment by mundosk8** [comment]
tested with node LTS & npm 5. I had some stress's with node 8 while ago, and downgraded to LTS version, since there didn't had any problem more. Maybe the source of your problem holds on that node version.

**Comment by codyc4321** [comment]
hmm, ok thanks

**Comment by mundosk8** [comment]
When you test it tell me if it was the cause of the problem.

**Comment by AdeleD** [comment]
The problem is on your side. See https://github.com/AdeleD/react-paginate/issues/170

**Pull request closed without merging**
