### PR TITLE
ES6 export

### PR DESCRIPTION
**Pull request by MonsieurV**
Use exclusively ES6 export

Should merge #175 before

### CODE REVIEW

**Comment by MonsieurV** [comment]
@AdeleD I updated the PR so we now only have the fix for #201 (and merge commits, I can remove them if you want)

**Comment by AdeleD** [comment]
Yes, could you remove the merge commits so that I can merge the PR please? Thank you so much.

**Comment by MonsieurV** [comment]
Done :)

**Comment by AdeleD** [comment]
Thank you!

**Pull request merged**
