### PR TITLE
Fixed bugs for react 0.14 Beta

### PR DESCRIPTION
**Pull request by tarkanlar**

### CODE REVIEW

**Comment by AdeleD** [comment]
Thank you for your work. I keep it in a branch called react-0.14 for the moment because this version of React isn't stable yet. A release candidate was announced yesterday (https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html). In the meantime react-paginate is supposed to work with react 0.13.

**Comment by tmoitie** [comment]
React 0.14 is released now, can this be merged please?

**Comment by AdeleD** [comment]
I recently rewrote this component with ES6 syntax so this PR has conflicts. I ported the changes into master branch so the component now works with React v0.14.

**Comment by tmoitie** [comment]
That's great! Thanks.

**Pull request closed without merging**
