### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by rafipiccolo**
allow react 17
see #330

### CODE REVIEW

**Review by andresgutgon — APPROVED** [review]

**Comment by imenesesl** [comment]
hi guys, it would be good to merge those changes, because the current version of react is compatible, and this library is blocking its use with higher versions  @AdeleD

**Comment by pawel2105** [comment]
Are there any workarounds?

**Comment by rafipiccolo** [comment]
Npm install --force
Or
Npm install --legacy-peer-deps
But a merge of my patch would be so much functional...

**Comment by pawel2105** [comment]
@rafipiccolo just found out about `npm i react-paginate --legacy-peer-deps` - thanks!

**Comment by AdeleD** [comment]
Merged and released. Thanks.

**Pull request merged**
