### PR TITLE
Adds props to extend accessibility support

### PR DESCRIPTION
**Pull request by erichsilvestre**

### CODE REVIEW

**Comment by zuber7** [comment]
@erichsilvestre , Can this be merged please? I need this feature.

**Comment by erichsilvestre** [comment]
> @erichsilvestre , Can this be merged please? I need this feature.

I wish it could be.

> @erichsilvestre , Can this be merged please? I need this feature.

@zuber7 I almost gave up on this MR lol.. the conflicts will be fixed today then we merge it.

**Comment by erichsilvestre** [comment]
@zuber7 I have resolved the conflicts

**Comment by zuber7** [comment]
> 
> 
> @zuber7 I have resolved the conflicts

Thanks @erichsilvestre . How can this be released in a new version?

**Comment by erichsilvestre** [comment]
> > @zuber7 I have resolved the conflicts
> 
> Thanks @erichsilvestre . How can this be released in a new version?

ask @AdeleD to merge it :D

**Comment by AdeleD** [comment]
I'm OK to add aria-label props on previous and next buttons. But I think the other props you add in this PR (`currentPageAriaLabel` and `pageAriaLabel`) are not necessary because you could probably do something like that:
```javascript
<PaginationBoxView
        initialPage={1}
        pageCount={3}
        ariaLabelBuilder={(page, selected) => selected ? 'The current page is page ' + page : 'It's page ' + page }
        extraAriaContext="some extra context" />
    );
```

**Comment by erichsilvestre** [comment]
@AdeleD it was 3y ago lol. I will check it and get back to you soon.

**Comment by AdeleD** [comment]
Sorry. And thank you.

**Comment by erichsilvestre** [comment]
@AdeleD are we good to go right now?

**Pull request merged**
