### PR TITLE
Add option to define rel attribute in next & previous button.

### PR DESCRIPTION
**Pull request by patelmayankce**
This change could be a good improvement for SEO.
REF: https://www.w3schools.com/tags/att_a_rel.asp

### CODE REVIEW

**Comment by patelmayankce** [comment]
@AdeleD , Plz check this PR and LMK your thoughts on this.

**Comment by patelmayankce** [comment]
@AdeleD , can you please take a look at this PR, I am really waiting for you to reply/merge it.

**Comment by AdeleD** [comment]
Thank you. I've released these rel attributes in react-paginate 7.0.0.

**Comment by patelmayankce** [comment]
Thanks!!

**Pull request merged**
