### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by fearintino**

### CODE REVIEW

**Comment by Vivekbhusal** [comment]
is it gonna take long to merge?

**Comment by Vivekbhusal** [comment]
@fearintino why did you close this?

**Comment by fearintino** [comment]
I'm sorry, but I do not fully understand you. It's my first  pull request😀. Please tell me, what should I do?

**Comment by Vivekbhusal** [comment]
@AdeleD any plan to merge this?

**Comment by fearintino** [comment]
Sure, if you will give me access

**Pull request closed without merging**
